apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: $GCE_DISK
  labels:
    app: $GCE_DISK
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: fast
  resources:
    requests:
      storage: 100Gi
