apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana-persistent-storage
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: fast
  gcePersistentDisk:
    fsType: ext4
    pdName: grafana-persistent-storage